title: Home
views:
  - path: default_view
    title: default_view
    badges:
      - person.tim
      - person.chantal
      - sensor.lights_on
      - sensor.power_consumption
      - sun.sun
    cards:
      - type: entities
        title: Huis
        state_color: true
        entities:
          - switch.mechanical_ventilation
          - input_boolean.night_mode
          - input_boolean.ghost_mode
          - input_boolean.notify_backyard_motion
          - input_boolean.automatic_vacuum_cleaner
          - script.cast_dashboard_office
          - input_select.guest_presence
        show_header_toggle: false
      - type: thermostat
        name: Verwarming
        entity: climate.heating
      - type: tile
        entity: alarm_control_panel.home_alarm
        features:
        - type: "alarm-modes"
          modes:
            - armed_home
            - armed_away
            - armed_night
            - disarmed
      - type: horizontal-stack
        cards:
          - type: tile
            entity: light.living_spots
            features:
              - type: light-brightness
          - type: tile
            entity: light.kitchen
            features:
              - type: light-brightness
      - type: entities
        title: Woonkamer & keuken
        state_color: true
        entities:
          - scene.living_normal
          - scene.living_movie
          - script.turn_lights_off
          - light.living_spots
          - light.kitchen
          - light.partylight
          - binary_sensor.living_motion_detection
          - binary_sensor.sliding_backdoor_is_open
          - sensor.netatmo_indoor_temperature
          - sensor.netatmo_indoor_humidity
          - sensor.netatmo_indoor_co2
          - sensor.living_temperature
          - sensor.living_humidity
          - sensor.living_illuminance
          - vacuum.xiaomi_vacuum_cleaner
          - script.empty_vacuum_cleaner
        show_header_toggle: false
      - type: entities
        title: Buiten
        state_color: true
        entities:
          - binary_sensor.backyard_motion_detection
          - light.backyard
          - light.gardendoor
          - light.buitenlicht_voorkant
          - sensor.netatmo_outdoor_temperature
          - sensor.netatmo_outdoor_humidity
          - sensor.backyard_temperature
          - sensor.backyard_illuminance
          - binary_sensor.shed_motion
          - sensor.shed_humidity
          - sensor.shed_temperature
        show_header_toggle: false
      - type: entities
        title: Gang BG
        state_color: true
        entities:
          - binary_sensor.frontdoor_is_open
          - binary_sensor.hallway_gf_smoke_alarm
          - light.gang_bg
          - sensor.hallway_gf_smoke_temperature
          - binary_sensor.voordeur_ding
          - binary_sensor.voordeur_motion
          - binary_sensor.hallway_motion_sensor
          - sensor.storage_temperature
          - sensor.storage_humidity
        show_header_toggle: false
      - type: entities
        title: Meterkast
        state_color: true
        entities:
          - sensor.fusebox_temperature
          - sensor.fusebox_humidity
      - type: entities
        title: Gang 1ste
        state_color: true
        entities:
          - binary_sensor.hallway_1st_motion_detection
          - binary_sensor.hallway_1st_smoke_alarm
          - light.hallway_1st
          - sensor.hallway_1st_temperature
          - sensor.hallway_1st_humidity
          - sensor.hallway_1st_illuminance
          - sensor.hallway_1st_smoke_temperature
        show_header_toggle: false
      - type: entities
        title: Gang 2de
        state_color: true
        entities:
          - binary_sensor.hallway_2nd_motion_detection
          - binary_sensor.carbon_monoxide_detected
          - light.hallway_2nd
          - sensor.hallway_2nd_temperature
          - sensor.hallway_2nd_humidity
          - sensor.hallway_2nd_illuminance
          - sensor.co_temperature
        show_header_toggle: false
      - type: entities
        title: Slaapkamer
        state_color: true
        entities:
          - sensor.masterbedroom_temperature
          - sensor.masterbedroom_humidity
        show_header_toggle: false
      - type: entities
        title: Slaapkamer Jens
        state_color: true
        entities:
          - binary_sensor.bedroom_jens_motion_detection
          - light.bedroom_jens
          - sensor.bedroom_jens_temperature
          - sensor.bedroom_jens_humidity
          - sensor.bedroom_jens_illuminance
        show_header_toggle: false
      - type: entities
        title: Slaapkamer Tygo
        state_color: true
        entities:
          - binary_sensor.tygo_motion_detection
          - light.bedroom_tygo
          - sensor.tygo_temperature
          - sensor.tygo_humidity
          - sensor.tygo_illuminance
        show_header_toggle: false
      - type: entities
        title: Werkkamer klein
        state_color: true
        entities:
          - light.led_strip_small_office
          - sensor.netatmo_bedroom_temperature
          - sensor.netatmo_bedroom_humidity
          - sensor.netatmo_bedroom_co2
        show_header_toggle: false
      - type: entities
        title: Werkkamer groot
        state_color: true
        entities:
          - light.large_office
          - sensor.office_large_temperature
          - sensor.office_large_humidity
        show_header_toggle: false
      - type: entities
        title: Badkamer 2de
        state_color: true
        entities:
          - sensor.bathroom_2nd_temperature
          - sensor.bathroom_2nd_humidity
        show_header_toggle: false
    icon: 'mdi:home-outline'
  - path: mediaplayers
    title: Media
    icon: mdi:youtube-tv
    badges: []
    cards:
      - type: vertical-stack
        title: TV
        cards:
          - type: media-control
            entity: media_player.sony_bravia_tv
          - type: media-control
            entity: media_player.chromekamer
          - type: media-control
            entity: media_player.master_bedroom_tv
          - type: media-control
            entity: media_player.slaapkamer
      - type: vertical-stack
        title: Sonos
        cards:
          - type: media-control
            entity: media_player.keuken
      - type: vertical-stack
        title: Assistants
        cards:
          - type: media-control
            entity: media_player.woonkamer_mini
          - type: media-control
            entity: media_player.first_floor
          - type: media-control
            entity: media_player.home_hub
          - type: media-control
            entity: media_player.werkkamer
  - path: cameras
    title: Cameras
    icon: mdi:cctv
    badges: []
    cards:
      - type: picture-entity
        entity: camera.txnas_frontyard_cam
      - type: picture-entity
        entity: camera.txnas_backyard
      - type: picture-entity
        entity: camera.txnas_babycam
      - type: picture-entity
        entity: camera.tygo_mainstream
      - type: picture-entity
        entity: camera.shed
      - type: picture-entity
        entity: camera.txnas_hallway
      - type: picture-entity
        entity: camera.doorbell
  - path: security
    title: Security
    icon: mdi:security
    cards:
      - type: entities
        state_color: true
        entities:
          - entity: binary_sensor.living_motion_detection
            secondary_info: last-changed
          - entity: binary_sensor.hallway_1st_motion_detection
            secondary_info: last-changed
          - entity: binary_sensor.hallway_2nd_motion_detection
            secondary_info: last-changed
          - entity: binary_sensor.bedroom_jens_motion_detection
            secondary_info: last-changed
          - entity: binary_sensor.tygo_motion_detection
            secondary_info: last-changed
          - entity: binary_sensor.hallway_motion_sensor
            secondary_info: last-changed
          - entity: binary_sensor.backyard_motion_detection
            secondary_info: last-changed
          - entity: binary_sensor.shed_motion
            secondary_info: last-changed
          - entity: binary_sensor.voordeur_motion
            secondary_info: last-changed
          - entity: binary_sensor.frontdoor_is_open
            secondary_info: last-changed
          - entity: binary_sensor.sliding_backdoor_is_open
            secondary_info: last-changed
        show_header_toggle: false
      - type: alarm-panel
        name: Alarm
        states:
          - arm_home
          - arm_away
          - arm_night
        entity: alarm_control_panel.home_alarm
  - path: floorplan
    title: Floorplan
    icon: mdi:floor-plan
    cards:
      - type: picture-elements
        image: /local/floorplan.png
        elements:
          - type: state-icon
            entity: light.living_spots
            style:
              top: 29%
              left: 68%
          - type: state-icon
            entity: light.living_spots
            style:
              top: 42%
              left: 36%
          - type: state-icon
            entity: light.kitchen
            style:
              top: 71%
              left: 69%
          - type: state-icon
            entity: light.backyard
            style:
              top: 10%
              left: 37%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.gardendoor
            style:
              top: 3%
              left: 30%
          - type: state-icon
            entity: binary_sensor.backyard_motion_detection
            style:
              top: 3%
              left: 21%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.buitenlicht_voorkant
            style:
              top: 85%
              left: 52%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.gang_bg
            style:
              top: 84%
              left: 39%
          - type: state-icon
            entity: binary_sensor.hallway_gf_smoke_alarm
            style:
              top: 80%
              left: 39%
          - type: state-label
            entity: sensor.netatmo_indoor_temperature
            style:
              top: 20%
              left: 29%
          - type: state-icon
            entity: binary_sensor.living_motion_detection
            style:
              top: 52%
              left: 82%
          - type: state-icon
            entity: binary_sensor.frontdoor_is_open
            style:
              top: 88.6%
              left: 48%
          - type: state-icon
            entity: vacuum.xiaomi_vacuum_cleaner
            style:
              top: 24%
              left: 19%
          - type: state-label
            entity: sensor.living_temperature
            style:
              top: 52%
              left: 71%
          - type: state-label
            entity: sensor.netatmo_outdoor_temperature
            style:
              top: 5%
              left: 60%
          - type: state-icon
            entity: media_player.sony_bravia_tv
            style:
              top: 29%
              left: 82%
          - type: state-icon
            entity: media_player.chromekamer
            style:
              top: 24%
              left: 82%
          - type: state-icon
            entity: media_player.woonkamer
            style:
              top: 34%
              left: 82%
          - type: state-icon
            entity: media_player.woonkamer_mini
            style:
              top: 20%
              left: 19%
          - type: state-icon
            entity: media_player.keuken
            style:
              top: 78%
              left: 82%
          - type: icon
            entity: camera.hallway
            icon: mdi:cctv
            style:
              top: 56%
              left: 21%
              transform: "scaleX(-1)"
          - type: icon
            entity: camera.frontyard
            icon: mdi:cctv
            style:
              top: 85%
              left: 65%
          - type: icon
            entity: camera.backyard
            icon: mdi:cctv
            style:
              top: 3%
              left: 50%
          - type: state-icon
            entity: binary_sensor.voordeur_motion
            style:
              top: 85%
              left: 58%
          - type: state-icon
            entity: climate.heating
            style:
              top: 61%
              left: 23%
          - type: state-label
            entity: sensor.nefit_temperature
            style:
              top: 52%
              left: 29%
      - type: map
        entities:
          - device_tracker.timmobile
          - device_tracker.in2013
        hours_to_show: 24
  - path: dashboard
    title: Dashboard
    icon: mdi:monitor-dashboard
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.living_spots
              - type: light
                entity: light.kitchen
              - type: light
                entity: light.backyard
              - type: light
                entity: light.hallway_1st
              - type: light
                entity: light.bedroom_jens
              - type: light
                entity: light.hallway_2nd
              - type: light
                entity: light.large_office
              - type: light
                entity: light.bedroom_tygo
          - type: horizontal-stack
            cards:
              - type: button
                entity: light.gang_bg
              - type: button
                entity: light.buitenlicht_voorkant
              - type: button
                entity: light.gardendoor
              - type: button
                entity: light.led_strip_small_office
              - type: button
                entity: input_boolean.night_mode
              - type: button
                entity: scene.living_normal
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_normal
              - type: button
                entity: scene.living_movie
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_movie
          - type: horizontal-stack
            cards:
              - type: picture-glance
                title: Frontyard
                entities:
                  - binary_sensor.voordeur_ding
                  - binary_sensor.voordeur_motion
                  - binary_sensor.frontdoor_is_open
                camera_image: camera.txnas_frontyard_cam
              - type: picture-glance
                title: Backyard
                entities:
                  - binary_sensor.backyard_motion_detection
                  - entity: sensor.netatmo_outdoor_temperature
                    show_state: true
                camera_image: camera.txnas_backyard
              - type: picture-glance
                title: Hallway
                entities:
                  - entity: sensor.hallway_gf_smoke_temperature
                    show_state: true
                camera_image: camera.txnas_hallway
              - type: picture-glance
                title: Last doorbell
                entities:
                  - entity: sensor.voordeur_last_ding
                    show_state: true
                camera_image: camera.doorbell
          - type: horizontal-stack
            cards:
              - type: button
                entity: binary_sensor.living_motion_detection
              - type: button
                entity: binary_sensor.hallway_1st_motion_detection
              - type: button
                entity: binary_sensor.hallway_2nd_motion_detection
              - type: button
                entity: binary_sensor.bedroom_jens_motion_detection
              - type: button
                entity: binary_sensor.tygo_motion_detection
              - type: button
                entity: binary_sensor.backyard_motion_detection
              - type: button
                entity: binary_sensor.shed_motion
              - type: button
                entity: binary_sensor.voordeur_motion
              - type: button
                entity: binary_sensor.frontdoor_is_open
              - type: button
                entity: binary_sensor.sliding_backdoor_is_open
          - type: horizontal-stack
            cards:
              - type: sensor
                name: Living
                graph: line
                detail: 2
                entity: sensor.living_temperature
              - type: sensor
                name: Outdoor
                graph: line
                detail: 2
                entity: sensor.netatmo_outdoor_temperature
              - type: sensor
                name: 1st floor hallway
                graph: line
                detail: 2
                entity: sensor.hallway_1st_temperature
              - type: sensor
                name: 2nd floor hallway
                graph: line
                detail: 2
                entity: sensor.hallway_2nd_temperature
              - type: sensor
                name: Jens
                graph: line
                detail: 2
                entity: sensor.bedroom_jens_temperature
              - type: sensor
                name: Small office
                graph: line
                detail: 2
                entity: sensor.netatmo_bedroom_temperature
              - type: sensor
                name: Living
                graph: line
                detail: 2
                entity: sensor.living_humidity
              - type: sensor
                name: Outdoor
                graph: line
                detail: 2
                entity: sensor.netatmo_outdoor_humidity
              - type: gauge
                entity: sensor.power_consumption
                name: Power
                max: 4000
                severity:
                  green: 0
                  yellow: 500
                  red: 1500
  - path: network
    title: Network
    icon: mdi:lan
    panel: true
    cards:
      - type: grid
        cards:
        - type: sensor
          name: Connected devices
          graph: line
          detail: 2
          entity: sensor.asuswrt_devices_connected
        - type: sensor
          name: Download speed
          graph: line
          detail: 2
          entity: sensor.asuswrt_download_speed
        - type: sensor
          name: Upload speed
          graph: line
          detail: 2
          entity: sensor.asuswrt_upload_speed
        - type: sensor
          name: Downloaded data
          graph: line
          detail: 2
          entity: sensor.asuswrt_download
        - type: sensor
          name: Uploaded data
          graph: line
          detail: 2
          entity: sensor.asuswrt_upload

