title: Home
views:
  - path: default_view
    title: default_view
    badges:
      - person.tim
      - person.chantal
      - sensor.lights_on
      - sensor.power_consumption
      - sun.sun
    cards:
      - type: entities
        title: Huis
        state_color: true
        entities:
          - switch.ventilatie_145
          - input_boolean.night_mode
          - input_boolean.ghost_mode
          - input_boolean.notify_backyard_motion
          - input_boolean.automatic_vacuum_cleaner
          - input_boolean.cast_dashboard
          - input_select.guest_presence
        show_header_toggle: false
      - type: thermostat
        name: Verwarming
        entity: climate.heating
      - type: alarm-panel
        name: Alarm
        states:
          - arm_home
          - arm_away
          - arm_night
        entity: alarm_control_panel.home_alarm
      - type: horizontal-stack
        cards:
          - type: light
            entity: light.woonkamer_spots_5
          - type: light
            entity: light.keuken_spots_7
      - type: entities
        title: Woonkamer & keuken
        state_color: true
        entities:
          - scene.living_normal
          - scene.living_movie
          - script.turn_lights_off
          - light.woonkamer_spots_5
          - light.keuken_spots_7
          - switch.kerstboom_279
          - binary_sensor.living_sensor_119
          - binary_sensor.schuifpui_266
          - sensor.netatmo_indoor_temperature
          - sensor.netatmo_indoor_humidity
          - sensor.netatmo_indoor_co2
          - sensor.living_temperature_128
          - sensor.living_humidity_131
          - sensor.living_lux_130
          - vacuum.xiaomi_vacuum_cleaner
          - script.empty_vacuum_cleaner
        show_header_toggle: false
      - type: entities
        title: Buiten
        state_color: true
        entities:
          - binary_sensor.backyard_sensor_201
          - light.buitenlicht_achter_6
          - light.licht_tuindeur_148
          - light.buitenlicht_voorkant_32
          - light.garden_lights_254
          - sensor.netatmo_outdoor_temperature
          - sensor.netatmo_outdoor_humidity
          - sensor.backyard_temp1_202
          - sensor.backyard_lux1_203
          - binary_sensor.shed_motion
          - sensor.shed_humidity
          - sensor.shed_temperature
        show_header_toggle: false
      - type: entities
        title: Gang BG
        state_color: true
        entities:
          - binary_sensor.voordeur_200
          - binary_sensor.rookmelder_bg_247
          - light.gang_licht_30
          - sensor.temperatuur_bg_248
          - binary_sensor.voordeur_ding
          - binary_sensor.voordeur_motion
          - binary_sensor.hallway_motion_sensor
          - sensor.storage_temperature
          - sensor.storage_humidity
        show_header_toggle: false
      - type: entities
        title: Gang 1ste
        state_color: true
        entities:
          - binary_sensor.gang_1ste_sensor_170
          - binary_sensor.rookmelder_1ste_284
          - light.overloop_licht_1ste_44
          - sensor.hallway1st_temp_182
          - sensor.hallway1st_humidity_184
          - sensor.hallway1st_lux_183
          - sensor.temperatuur_1ste_285
        show_header_toggle: false
      - type: entities
        title: Gang 2de
        state_color: true
        entities:
          - binary_sensor.gang_2de_sensor_260
          - binary_sensor.rookmelder_2de_280
          - binary_sensor.co_sensor_255
          - light.overloop_licht_2de_132
          - sensor.hallway2nd_temp_261
          - sensor.hallway2nd_humidity_263
          - sensor.hallway2nd_lux_262
          - sensor.temperatuur_2de_281
          - sensor.temperature_sensor_256
        show_header_toggle: false
      - type: entities
        title: Slaapkamer
        state_color: true
        entities:
          - sensor.netatmo_bedroom_temperature
          - sensor.netatmo_bedroom_humidity
          - sensor.netatmo_bedroom_co2
        show_header_toggle: false
      - type: entities
        title: Babykamer
        state_color: true
        entities:
          - binary_sensor.babyroom_sensor_216
          - light.light_babyroom_208
          - sensor.babyroom_temp_217
          - sensor.babyroom_humidity_219
          - sensor.babyroom_lux_218
        show_header_toggle: false
      - type: entities
        title: Tygo's kamer
        state_color: true
        entities:
          - binary_sensor.tygo_sensor_274
          - light.slaapkamer_tygo_257
          - sensor.tygo_temperature_275
          - sensor.tygo_humidity_277
          - sensor.tygo_lux_276
        show_header_toggle: false
      - type: entities
        title: Werkkamer klein
        state_color: true
        entities:
          - light.led_strip_small_office
        show_header_toggle: false
      - type: entities
        title: Werkkamer groot
        state_color: true
        entities:
          - light.werkkamer_licht_152
        show_header_toggle: false
    icon: 'mdi:home-outline'
  - path: mediaplayers
    title: Media
    icon: mdi:youtube-tv
    badges: []
    cards:
      - type: vertical-stack
        title: TV
        cards:
          - type: media-control
            entity: media_player.sony_bravia_tv
          - type: media-control
            entity: media_player.chromekamer
          - type: media-control
            entity: media_player.master_bedroom_tv
          - type: media-control
            entity: media_player.slaapkamer
      - type: vertical-stack
        title: Sonos
        cards:
          - type: media-control
            entity: media_player.keuken
      - type: vertical-stack
        title: Assistants
        cards:
          - type: media-control
            entity: media_player.woonkamer_mini
          - type: media-control
            entity: media_player.first_floor
          - type: media-control
            entity: media_player.home_hub
  - path: cameras
    title: Cameras
    icon: mdi:cctv
    badges: []
    cards:
      - type: picture-entity
        entity: camera.frontyard
      - type: picture-entity
        entity: camera.backyard
      - type: picture-entity
        entity: camera.shed
      - type: picture-entity
        entity: camera.hallway
      - type: picture-entity
        entity: camera.doorbell
  - path: security
    title: Security
    icon: mdi:security
    cards:
      - type: entities
        state_color: true
        entities:
          - entity: binary_sensor.living_sensor_119
            secondary_info: last-changed
          - entity: binary_sensor.gang_1ste_sensor_170
            secondary_info: last-changed
          - entity: binary_sensor.gang_2de_sensor_260
            secondary_info: last-changed
          - entity: binary_sensor.babyroom_sensor_216
            secondary_info: last-changed
          - entity: binary_sensor.tygo_sensor_274
            secondary_info: last-changed
          - entity: binary_sensor.hallway_motion_sensor
            secondary_info: last-changed
          - entity: binary_sensor.backyard_sensor_201
            secondary_info: last-changed
          - entity: binary_sensor.shed_motion
            secondary_info: last-changed
          - entity: binary_sensor.voordeur_motion
            secondary_info: last-changed
          - entity: binary_sensor.voordeur_200
            secondary_info: last-changed
          - entity: binary_sensor.schuifpui_266
            secondary_info: last-changed
        show_header_toggle: false
      - type: alarm-panel
        name: Alarm
        states:
          - arm_home
          - arm_away
          - arm_night
        entity: alarm_control_panel.home_alarm
  - path: floorplan
    title: Floorplan
    icon: mdi:floor-plan
    cards:
      - type: picture-elements
        image: /local/floorplan.png
        elements:
          - type: state-icon
            entity: light.woonkamer_spots_5
            style:
              top: 29%
              left: 68%
          - type: state-icon
            entity: light.woonkamer_spots_5
            style:
              top: 42%
              left: 36%
          - type: state-icon
            entity: light.keuken_spots_7
            style:
              top: 71%
              left: 69%
          - type: state-icon
            entity: light.buitenlicht_achter_6
            style:
              top: 10%
              left: 37%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.licht_tuindeur_148
            style:
              top: 3%
              left: 30%
          - type: state-icon
            entity: binary_sensor.backyard_sensor_201
            style:
              top: 3%
              left: 21%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.buitenlicht_voorkant_32
            style:
              top: 85%
              left: 52%
          - type: state-icon
            tap_action:
              action: toggle
            entity: light.gang_licht_30
            style:
              top: 84%
              left: 39%
          - type: state-icon
            entity: binary_sensor.rookmelder_bg_247
            style:
              top: 80%
              left: 39%
          - type: state-label
            entity: sensor.netatmo_indoor_temperature
            style:
              top: 20%
              left: 29%
          - type: state-icon
            entity: binary_sensor.living_sensor_119
            style:
              top: 52%
              left: 82%
          - type: state-icon
            entity: binary_sensor.voordeur_200
            style:
              top: 88.6%
              left: 48%
          - type: state-icon
            entity: vacuum.xiaomi_vacuum_cleaner
            style:
              top: 24%
              left: 19%
          - type: state-label
            entity: sensor.living_temperature_128
            style:
              top: 52%
              left: 71%
          - type: state-label
            entity: sensor.netatmo_outdoor_temperature
            style:
              top: 5%
              left: 60%
          - type: state-icon
            entity: media_player.sony_bravia_tv
            style:
              top: 29%
              left: 82%
          - type: state-icon
            entity: media_player.chromekamer
            style:
              top: 24%
              left: 82%
          - type: state-icon
            entity: media_player.woonkamer
            style:
              top: 34%
              left: 82%
          - type: state-icon
            entity: media_player.woonkamer_mini
            style:
              top: 20%
              left: 19%
          - type: state-icon
            entity: media_player.keuken
            style:
              top: 78%
              left: 82%
          - type: icon
            entity: camera.hallway
            icon: mdi:cctv
            style:
              top: 56%
              left: 21%
              transform: "scaleX(-1)"
          - type: icon
            entity: camera.frontyard
            icon: mdi:cctv
            style:
              top: 85%
              left: 65%
          - type: icon
            entity: camera.backyard
            icon: mdi:cctv
            style:
              top: 3%
              left: 50%
          - type: state-icon
            entity: binary_sensor.voordeur_motion
            style:
              top: 85%
              left: 58%
          - type: state-icon
            entity: climate.heating
            style:
              top: 61%
              left: 23%
          - type: state-label
            entity: sensor.nefit_temperature
            style:
              top: 52%
              left: 29%
      - type: map
        entities:
          - device_tracker.tim_mobile
          - device_tracker.in2013
        hours_to_show: 24
  - path: dashboard
    title: Dashboard
    icon: mdi:monitor-dashboard
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.woonkamer_spots_5
              - type: light
                entity: light.keuken_spots_7
              - type: light
                entity: light.buitenlicht_achter_6
              - type: light
                entity: light.overloop_licht_1ste_44
              - type: light
                entity: light.light_babyroom_208
              - type: light
                entity: light.overloop_licht_2de_132
              - type: light
                entity: light.werkkamer_licht_152
              - type: light
                entity: light.slaapkamer_tygo_257
          - type: horizontal-stack
            cards:
              - type: button
                entity: light.gang_licht_30
              - type: button
                entity: light.buitenlicht_voorkant_32
              - type: button
                entity: light.licht_tuindeur_148
              - type: button
                entity: light.garden_lights_254
              - type: button
                entity: input_boolean.night_mode
              - type: button
                entity: input_boolean.automatic_vacuum_cleaner
              - type: button
                entity: scene.living_normal
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_normal
              - type: button
                entity: scene.living_movie
                tap_action:
                  action: call-service
                  service: scene.turn_on
                  service_data:
                    entity_id: scene.living_movie
              - type: button
                entity: sensor.wasmachine_operation_state
              - type: button
                entity: binary_sensor.wash_dryer_state
          - type: horizontal-stack
            cards:
              - type: picture-glance
                title: Frontyard
                entities:
                  - binary_sensor.voordeur_ding
                  - binary_sensor.voordeur_motion
                  - binary_sensor.voordeur_200
                camera_image: camera.frontyard
              - type: picture-glance
                title: Backyard
                entities:
                  - binary_sensor.backyard_sensor_201
                  - entity: sensor.netatmo_outdoor_temperature
                    show_state: true
                camera_image: camera.backyard
              - type: picture-glance
                title: Hallway
                entities:
                  - entity: sensor.temperatuur_bg_248
                    show_state: true
                camera_image: camera.hallway
              - type: picture-glance
                title: Last doorbell
                entities:
                  - entity: sensor.voordeur_last_ding
                    show_state: true
                camera_image: camera.doorbell
          - type: horizontal-stack
            cards:
              - type: button
                entity: binary_sensor.living_sensor_119
              - type: button
                entity: binary_sensor.gang_1ste_sensor_170
              - type: button
                entity: binary_sensor.gang_2de_sensor_260
              - type: button
                entity: binary_sensor.babyroom_sensor_216
              - type: button
                entity: binary_sensor.backyard_sensor_201
              - type: button
                entity: binary_sensor.shed_motion
              - type: button
                entity: binary_sensor.voordeur_motion
              - type: button
                entity: binary_sensor.voordeur_200
              - type: button
                entity: binary_sensor.schuifpui_266
          - type: horizontal-stack
            cards:
              - type: sensor
                name: Living
                graph: line
                detail: 2
                entity: sensor.living_temperature_128
              - type: sensor
                name: Outdoor
                graph: line
                detail: 2
                entity: sensor.netatmo_outdoor_temperature
              - type: sensor
                name: 1st floor hallway
                graph: line
                detail: 2
                entity: sensor.hallway1st_temp_182
              - type: sensor
                name: 2nd floor hallway
                graph: line
                detail: 2
                entity: sensor.hallway2nd_temp_261
              - type: sensor
                name: Babyroom
                graph: line
                detail: 2
                entity: sensor.babyroom_temp_217
              - type: sensor
                name: Master bedroom
                graph: line
                detail: 2
                entity: sensor.netatmo_bedroom_temperature
              - type: sensor
                name: Living
                graph: line
                detail: 2
                entity: sensor.living_humidity_131
              - type: sensor
                name: Outdoor
                graph: line
                detail: 2
                entity: sensor.netatmo_outdoor_humidity
              - type: gauge
                entity: sensor.power_consumption
                max: 10
                severity:
                  green: 0
                  yellow: 1
                  red: 3
  - path: network
    title: Network
    icon: mdi:lan
    panel: true
    cards:
      - type: grid
        cards:
        - type: sensor
          name: Connected devices
          graph: line
          detail: 2
          entity: sensor.asuswrt_devices_connected
        - type: sensor
          name: Download speed
          graph: line
          detail: 2
          entity: sensor.asuswrt_download_speed
        - type: sensor
          name: Upload speed
          graph: line
          detail: 2
          entity: sensor.asuswrt_upload_speed
        - type: sensor
          name: Downloaded data
          graph: line
          detail: 2
          entity: sensor.asuswrt_download
        - type: sensor
          name: Uploaded data
          graph: line
          detail: 2
          entity: sensor.asuswrt_upload
        - type: sensor
          name: Vera response time
          graph: line
          detail: 2
          entity: sensor.vera_response_time

