- platform: template
  sensors:
    wash_dryer_state:
      friendly_name: 'Wash dryer'
      delay_on:
        seconds: 60
      delay_off:
        seconds: 60
      value_template: "{{ states('sensor.washdryer_electric_consumption_w')|int(0) > 4 }}"
    hotwater_active:
      friendly_name: 'Hot Water'
      value_template: "{{ state_attr('climate.heating', 'boiler_indicator') == 'HW' }}"
- platform: trend
  sensors:
    voltage_sags:
      entity_id: sensor.voltage_sags_phase_l1
    voltage_swells:
      entity_id: sensor.voltage_swells_phase_l1
- platform: group
  name: "Backyard motion sensors"
  device_class: motion
  entities:
    - binary_sensor.backyard_animal
    - binary_sensor.backyard_person
    - binary_sensor.backyard_vehicle
    - binary_sensor.backyard_motion
    - binary_sensor.backyard_motion_detection