- platform: template
  sensors:
    wash_dryer_state:
      friendly_name: 'Wash dryer'
      delay_on:
        seconds: 15
      value_template: >
        {% if states.switch.wasmachine_37 %}
          {{ states.switch.wasmachine_37.attributes.current_power_w > 2 }}
        {% endif %}
    washing_machine_state:
      friendly_name: 'Washing machine'
      delay_off:
        minutes: 1
      value_template: >
        {% if as_timestamp(states('sensor.wasmachine_remaining_program_time')) < as_timestamp(now()) %}
        true
        {% elif states('sensor.wasmachine_remaining_program_time') == 'unavailable' %}
        true
        {% endif %}
- platform: mqtt
  name: 'Shed sensor'
  state_topic: shed/binary_sensor/shed_motion/state
  availability_topic: shed/status
  device_class: motion
- platform: ping
  host: 192.168.150.10
  name: Ping to Vera
- platform: trend
  sensors:
    voltage_sags:
      entity_id: sensor.voltage_sags_phase_l1
    voltage_swells:
      entity_id: sensor.voltage_swells_phase_l1
