- platform: rest
  scan_interval: 00:05:00
  resource: https://api.ipify.org?format=json
  name: External IP
  value_template: "{{ value_json.ip }}"
- platform: derivative
  name: Hourly Gas Consumption
  source: sensor.gas_consumption
  unit_time: h
  time_window: "00:01:00"
- platform: derivative
  name: Solar Production Power
  source: sensor.solaredge_i1_ac_energy
  unit_time: h
  time_window: "00:01:00"