- platform: template
  sensors:
    nefit_temperature:
      friendly_name: 'Nefit Temperature'
      value_template: "{{ state_attr('climate.heating', 'current_temperature') }}"
      unit_of_measurement: '°C'
    lights_on:
      friendly_name: 'Lights that are on'
      value_template: "{{ states.light|selectattr('state', 'equalto', 'on')|list|length }}"
      unit_of_measurement: lights
- platform: rest
  scan_interval: 00:05:00
  resource: http://ip.jsontest.com
  name: External IP
  value_template: "{{ value_json.ip }}"
- platform: derivative
  name: Hourly Gas Consumption
  source: sensor.gas_consumption
  unit_time: h
  time_window: "00:01:00"
