- platform: yr
  name: Weather forecast
  forecast: 8
  monitored_conditions:
    - windSpeed
    - windDirection
- platform: ring
- platform: mqtt
  name: 'Shed Temperature'
  state_topic: shed/sensor/shed_temperature/state
  availability_topic: shed/status
  unit_of_measurement: '°C'
- platform: mqtt
  name: 'Shed Humidity'
  state_topic: shed/sensor/shed_humidity/state
  availability_topic: shed/status
  unit_of_measurement: '%'
- platform: template
  sensors:
    nefit_temperature:
      friendly_name: 'Nefit Temperature'
      value_template: '{{ states.climate.heating.attributes.current_temperature }}'
      unit_of_measurement: '°C'
- platform: mqtt
  name: plant_1_moisture
  state_topic: home/plants/plant1/
  value_template: '{{ value_json.moisture }}'
  device_class: humidity
  unit_of_measurement: '%'
- platform: mqtt
  name: plant_1_battery
  state_topic: home/plants/plant1/
  value_template: '{{ value_json.battery }}'
  device_class: battery
  unit_of_measurement: '%'
- platform: mqtt
  name: plant_1_temperature
  state_topic: home/plants/plant1/
  value_template: '{{ value_json.temperature }}'
  device_class: temperature
  unit_of_measurement: '°C'
- platform: mqtt
  name: plant_1_conductivity
  state_topic: home/plants/plant1/
  value_template: '{{ value_json.conductivity }}'
  unit_of_measurement: 'μS/cm'
- platform: mqtt
  name: plant_1_brightness
  state_topic: home/plants/plant1/
  value_template: '{{ value_json.brightness }}'
  device_class: illuminance
  unit_of_measurement: 'lux'
- platform: mqtt
  name: plant_2_moisture
  state_topic: home/plants/plant2/
  value_template: '{{ value_json.moisture }}'
  device_class: humidity
  unit_of_measurement: '%'
- platform: mqtt
  name: plant_2_battery
  state_topic: home/plants/plant2/
  value_template: '{{ value_json.battery }}'
  device_class: battery
  unit_of_measurement: '%'
- platform: mqtt
  name: plant_2_temperature
  state_topic: home/plants/plant2/
  value_template: '{{ value_json.temperature }}'
  device_class: temperature
  unit_of_measurement: '°C'
- platform: mqtt
  name: plant_2_conductivity
  state_topic: home/plants/plant2/
  value_template: '{{ value_json.conductivity }}'
  unit_of_measurement: 'μS/cm'
- platform: mqtt
  name: plant_2_brightness
  state_topic: home/plants/plant2/
  value_template: '{{ value_json.brightness }}'
  device_class: illuminance
  unit_of_measurement: 'lux'
- platform: dsmr
  host: 192.168.150.11
  port: 6000
  dsmr_version: 5
