- platform: template
  sensors:
    nefit_temperature:
      friendly_name: 'Nefit Temperature'
      value_template: '{{ states.climate.heating.attributes.current_temperature }}'
      unit_of_measurement: '°C'
- platform: dsmr
  host: 192.168.150.11
  port: 6000
  dsmr_version: 5
