- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_sensor_119
      to: 'on'
    - platform: state
      entity_id: binary_sensor.gang_1ste_sensor_170
      to: 'on'
    - platform: state
      entity_id: binary_sensor.gang_2de_sensor_260
      to: 'on'
    - platform: state
      entity_id: binary_sensor.babyroom_sensor_216
      to: 'on'
    - platform: state
      entity_id: binary_sensor.voordeur_200
      to: 'on'
    - platform: state
      entity_id: binary_sensor.schuifpui_249
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: triggered
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - service: script.notify_of_movement

- alias: 'Trigger alarm while armed night'
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur_200
      to: 'on'
    - platform: state
      entity_id: binary_sensor.schuifpui_249
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_night
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: triggered
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - service: script.notify_of_movement

- alias: 'Trigger alarm while armed home'
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur_200
      to: 'on'
    - platform: state
      entity_id: binary_sensor.schuifpui_249
      to: 'on'
    - platform: state
      entity_id: binary_sensor.backyard_sensor_201
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: triggered
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - service: script.notify_of_movement

- alias: 'Activate alarm when away'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
  action:
    - service: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm

- alias: 'Activate alarm when asleep'
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - service: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.home_alarm

- alias: 'Deactivate away and night alarm when home or awake '
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'home'
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'off'
  condition:
    - condition: not
      conditions:
      - condition: state
        entity_id: alarm_control_panel.home_alarm
        state: disarmed
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm

- alias: 'Notify of alarm'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: triggered
  action:
    - service: notify.all
      data_template:
        title: '🚨 *Inbraak alarm!*'
        message: 'Het inbraakalarm is geactiveerd! Status: {{ trigger.from_state.state|default("unknown")|replace("_", " ") }}'
        data:
          inline_keyboard:
            - 'Blink lights:/blinklights'
            - 'Disarm alarm:/disarm_alarm'
