- alias: 'Activate alarm when away'
  trigger:
    - trigger: state
      entity_id: group.all_persons
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.guest_presence
      state: 'off'
  action:
    - action: notify.app_tim
      data:
        title: "🛡️ Alarm activatie"
        message: "Alarm wordt geactiveerd omdat iedereen weg is."
        data:
          notification_icon: mdi:shield-alert
          actions:
            - action: "disarm_alarm"
              title: "Alarm uitschakelen"
    - action: alarm_control_panel.alarm_arm_away
      entity_id: alarm_control_panel.home_alarm

- alias: 'Activate alarm when asleep'
  trigger:
    - trigger: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - action: alarm_control_panel.alarm_arm_night
      entity_id: alarm_control_panel.home_alarm

- alias: 'Deactivate night alarm when waking up'
  trigger:
    - trigger: time
      at: '06:30:00'
  condition:
    - condition: time
      after: '06:30:00'
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_night
  action:
    - action: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm

- alias: 'Deactivate away alarm when home'
  trigger:
    - trigger: state
      entity_id: group.all_persons
      to: 'home'
  condition:
    - condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
  action:
    - action: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm
    - action: notify.app_tim
      data:
        title: "🛡️ Alarm deactivatie"
        message: "Alarm gedeactiveerd."
        data:
          notification_icon: mdi:shield-check

- alias: 'Disarm alarm event'
  trigger:
    - trigger: event
      event_type: mobile_app_notification_action
      event_data:
        action: disarm_alarm
  action:
    - action: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm
    - action: notify.app_tim
      data:
        title: "🛡️ Alarm deactivatie"
        message: "Alarm gedeactiveerd."
        data:
          notification_icon: mdi:shield-check