- alias: 'Trigger alarm while armed away'
  trigger:
    - trigger: state
      entity_id:
        - binary_sensor.living_motion_detection
        - binary_sensor.hallway_gf_motion
        - binary_sensor.hallway_1st_motion_detection
        - binary_sensor.hallway_2nd_motion_detection
        - binary_sensor.bedroom_jens_motion_detection
        - binary_sensor.tygo_motion_detection
        - binary_sensor.voordeur_opening
        - binary_sensor.schuifpui_opening
        - binary_sensor.backyard_person
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_away
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: triggered
  action:
    - action: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - action: script.notify_of_movement

- alias: 'Trigger alarm while armed night'
  trigger:
    - trigger: state
      entity_id: binary_sensor.voordeur_opening
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.schuifpui_opening
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_night
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: triggered
  action:
    - action: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - action: script.notify_of_movement

- alias: 'Trigger alarm while armed home'
  trigger:
    - trigger: state
      entity_id:
        - binary_sensor.voordeur_opening
        - binary_sensor.schuifpui_opening
        - binary_sensor.backyard_motion_detection
        - binary_sensor.backyard_person
        - binary_sensor.shed_motion
      to: 'on'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: armed_home
        - condition: state
          entity_id: alarm_control_panel.home_alarm
          state: triggered
  action:
    - action: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.home_alarm
    - action: script.notify_of_movement

- alias: 'Notify of alarm'
  trigger:
    - trigger: state
      entity_id: alarm_control_panel.home_alarm
      to: triggered
  action:
    - action: notify.send_message
      target:
        entity_id: !secret telegram_notify_bot
      data_template:
        title: '🚨 *Inbraak alarm!*'
        message: 'Het inbraakalarm is geactiveerd!'
        data:
          inline_keyboard:
            - 'Blink lights:/blinklights'
            - 'Disarm alarm:/disarm_alarm'