- alias: 'Notify when UPS running on battery'
  trigger:
    - trigger: state
      entity_id: sensor.ups_status
  action:
    - action: notify.send_message
      target:
        entity_id: !secret telegram_notify_bot
      data_template:
        title: '⚠️ *UPS status*'
        message: "UPS changed status to {{ states('sensor.ups_status') }}"

- alias: 'Shutdown NAS when running on UPS battery'
  trigger:
    - trigger: numeric_state
      entity_id: sensor.ups_time_on_battery
      above: 60
  action:
    - action: notify.send_message
      target:
        entity_id: !secret telegram_notify_bot
      data_template:
        title: '⚠️ *UPS status*'
        message: 'NAS will be shutdown'
    - action: synology_dsm.shutdown