- alias: 'Turn on Babyroom light when motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.babyroom_sensor_216
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: numeric_state
          entity_id: sensor.babyroom_lux_218
          below: 1
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.light_babyroom_208
        brightness: 140

- alias: 'Turn off Babyroom light'
  trigger:
    - platform: state
      entity_id: binary_sensor.babyroom_sensor_216
      to: 'off'
      for:
        minutes: 5
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
  condition:
    - condition: state
      entity_id: light.light_babyroom_208
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.light_babyroom_208
