- alias: 'Turn on backyard door light when motion'
  trigger:
    - trigger: state
      entity_id: binary_sensor.backyard_motion_detection
      to: 'on'
    - trigger: state
      entity_id: binary_sensor.backyard_person
      to: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: "+00:20:00"
  action:
    - action: light.turn_on
      data:
        entity_id: light.backyarddoor_light
    - delay: '00:02:00'
    - action: light.turn_off
      data:
        entity_id: light.backyarddoor_light

- alias: 'Turn off backyard door light'
  trigger:
    - trigger: state
      entity_id: binary_sensor.backyard_motion_detection
      to: 'off'
  condition:
    - condition: state
      entity_id: light.backyarddoor_light
      state: 'on'
  action:
    - action: light.turn_off
      entity_id: light.backyarddoor_light
