- alias: 'Turn on garden spot lights'
  trigger:
    - trigger: state
      entity_id: input_select.home_mode
      from: away
      to: home
    - trigger: state
      entity_id: binary_sensor.living_motion_detection
      to: 'on'
    - trigger: sun
      event: 'sunset'
      offset: '+00:20:00'
  condition:
    - condition: state
      entity_id: input_select.home_mode
      state: home
    - condition: state
      entity_id: light.tuin_spots
      state: 'off'
    - condition: or
      conditions:
      - condition: sun
        after: 'sunset'
        after_offset: '+00:20:00'
      - condition: sun
        before: 'sunrise'
        before_offset: '-00:15:00'
  action:
    - action: light.turn_on
      data:
        entity_id: light.tuin_spots

- alias: 'Turn off garden spot lights'
  trigger:
    - trigger: sun
      event: 'sunrise'
      offset: '-00:15:00'
    - trigger: state
      entity_id: input_select.home_mode
      to:
        - away
        - night
  action:
    - action: light.turn_off
      data:
        entity_id: light.tuin_spots

- alias: 'Turn on backyard spot when person detected'
  trigger:
    - trigger: state
      entity_id: binary_sensor.backyard_person
      to: 'on'
  condition:
    - condition: sun
      after: sunset
      after_offset: "+00:20:00"
  action:
    - action: light.turn_on
      data:
        entity_id: light.backyard
        brightness: 25
    - delay: '00:02:00'
    - action: light.turn_off
      data:
        entity_id: light.backyard