- alias: 'Turn on backyard light'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'home'
    - platform: sun
      event: 'sunset'
      offset: '+00:30:00'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: light.buitenlicht_achter_6
      state: 'off'
    - condition: sun
      after: 'sunset'
      after_offset: '+00:30:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.buitenlicht_achter_6
        brightness: 25

- alias: 'Turn off backyard light'
  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '-00:30:00'
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
  action:
    - service: light.turn_off
      data:
        entity_id: light.buitenlicht_achter_6

- alias: 'Raise brightness of backyard light when motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.backyard_sensor_201
      to: 'on'
  condition:
    - condition: state
      entity_id: light.buitenlicht_achter_6
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.buitenlicht_achter_6
        brightness: 100

- alias: 'Dim brightness of backyard light'
  trigger:
    - platform: state
      entity_id: binary_sensor.backyard_sensor_201
      to: 'off'
  condition:
    - condition: state
      entity_id: light.buitenlicht_achter_6
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.buitenlicht_achter_6
        brightness: 25
