- alias: 'Trigger notification when motion in backyard'
  trigger:
    - platform: state
      entity_id: binary_sensor.achtertuin_sensor
      state: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.notify_backyard_motion
      state: 'on'
  action:
    - service: notify.all
    - service: notify.telegram_notify
      data_template:
        message: "Beweging in achtertuin"
        data:
          photo:
            - url: "http://127.0.0.1:8123{{ states.camera.backyard.attributes.entity_picture }}"
              caption: Beweging in achtertuin

- alias: 'Trigger notification when motion in shed'
  trigger:
    - platform: state
      entity_id: binary_sensor.shed_sensor
      state: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.notify_backyard_motion
      state: 'on'
  action:
    - service: notify.all
    - service: notify.telegram_notify
      data_template:
        message: "Beweging in schuur"
        data:
          photo:
            - url: "http://127.0.0.1:8123{{ states.camera.backyard.attributes.entity_picture }}"
              caption: Beweging in de schuur
