- alias: 'Turn on backyard Chistmas lights'
  trigger:
    - trigger: state
      entity_id: group.all_persons
      to: 'home'
    - trigger: state
      entity_id: binary_sensor.living_motion_detection
      to: 'on'
    - trigger: sun
      event: 'sunset'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: light.backyard_christmas
      state: 'off'
    - condition: or
      conditions:
      - condition: sun
        after: 'sunset'
      - condition: sun
        before: 'sunrise'
  action:
    - action: light.turn_on
      data:
        entity_id: light.backyard_christmas

- alias: 'Turn off backyard Christmas lights'
  trigger:
    - trigger: sun
      event: 'sunrise'
    - trigger: state
      entity_id: group.all_persons
      to: 'not_home'
    - trigger: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - action: light.turn_off
      data:
        entity_id: light.backyard_christmas