- alias: 'Turn on backyard door light when motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.backyard_motion_detection
      to: 'on'
    - platform: state
      entity_id: binary_sensor.backyard_person
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      data:
        entity_id: light.gardendoor

- alias: 'Turn off backyard door light'
  trigger:
    - platform: state
      entity_id: binary_sensor.backyard_motion_detection
      to: 'off'
  condition:
    - condition: state
      entity_id: light.gardendoor
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.gardendoor
