- alias: 'Turn on garden spot lights'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'home'
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'on'
    - platform: sun
      event: 'sunset'
      offset: '+00:20:00'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: light.tuin_spots
      state: 'off'
    - condition: or
      conditions:
      - condition: sun
        after: 'sunset'
        after_offset: '+00:20:00'
      - condition: sun
        before: 'sunrise'
        before_offset: '-00:15:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.tuin_spots

- alias: 'Turn off garden spot lights'
  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '-00:15:00'
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - service: light.turn_off
      data:
        entity_id: light.tuin_spots

- alias: 'Turn on backyard spot when person detected'
  trigger:
    - platform: state
      entity_id: binary_sensor.backyard_person
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      data:
        entity_id: light.backyard
        brightness: 25
    - delay: '00:03:00'
    - service: light.turn_off
      data:
        entity_id: light.backyard