- alias: 'Notify when motion in backyard'
  trigger:
    - platform: state
      entity_id:
        - binary_sensor.backyard_motion_detection
        - binary_sensor.backyard_person
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.notify_backyard_motion
      state: 'on'
  action:
    - service: notify.telegram_notify
      data_template:
        message: "Beweging in achtertuin"
        data:
          photo:
            - url: "http://127.0.0.1:8123{{ states.camera.txnas_backyard.attributes.entity_picture }}"
              caption: Backyard

- alias: 'Notify when motion in shed'
  trigger:
    - platform: state
      entity_id: binary_sensor.shed_motion
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.notify_backyard_motion
      state: 'on'
  action:
    - service: notify.telegram_notify
      data_template:
        message: "Beweging in schuur"
        data:
          photo:
            - url: "http://127.0.0.1:8123{{ states.camera.txnas_backyard.attributes.entity_picture }}"
              caption: Backyard
