- alias: 'Turn on backyard door light when motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.backyard_sensor_201
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: light.turn_on
      data:
        entity_id: light.licht_tuindeur_148

- alias: 'Turn off backyard door light'
  trigger:
    - platform: state
      entity_id: binary_sensor.backyard_sensor_201
      to: 'off'
  condition:
    - condition: state
      entity_id: light.licht_tuindeur_148
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.licht_tuindeur_148
