- alias: 'Disable camera privacy when alarm is armed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_home'
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_night'
  action:
    - service: rest_command.disable_privacy_mode

- alias: 'Enable camera privacy when alarm is disarmed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'disarmed'
  action:
    - service: rest_command.enable_privacy_mode

