- alias: 'Christmas lights on when motion in living'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_sensor_119
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: light.christmas_tree_253
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.christmas_tree_253
    - service: light.turn_on
      entity_id: light.christmas_star_251

- alias: 'Christmas lights off when leaving or sleeping'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - service: light.turn_off
      entity_id: light.christmas_tree_253
    - service: light.turn_off
      entity_id: light.christmas_star_251

- alias: 'Christmas star off when not home'
  trigger:
    - platform: time
      at: '23:30:00'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'not_home'
  action:
    - service: light.turn_off
      entity_id: light.christmas_star_251

- alias: 'Christmas star on when sun goes down and not home'
  trigger:
    - platform: sun
      event: 'sunset'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'not_home'
  action:
    - service: light.turn_on
      entity_id: light.christmas_star_251
