- alias: 'Christmas lights on when motion in living'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_sensor
      state: 'on'
    - platform: state
      entity_id: group.all_devices
      state: 'home'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: switch.kerstboom
      state: 'off'
    - condition: state
      entity_id: switch.kerstdorp
      state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.kerstboom
    - service: switch.turn_on
      entity_id: switch.kerstdorp

- alias: 'Christmas lights off when leaving or sleeping'
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'not_home'
    - platform: state
      entity_id: input_boolean.night_mode
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.kerstboom
    - service: switch.turn_off
      entity_id: switch.kerstdorp

