- alias: "Turn on Christmas lights"
  trigger:
    - trigger: state
      entity_id: group.all_persons
      to: 'home'
    - trigger: state
      entity_id: binary_sensor.living_motion_detection
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
  action:
    - action: light.turn_on
      entity_id:
        - light.christmas_tree_switch
        - light.christmas_star
        - light.tv_christmas

- alias: "Turn off Christmas lights"
  trigger:
    - trigger: state
      entity_id: input_boolean.night_mode
      to: 'on'
    - trigger: state
      entity_id: group.all_persons
      to: 'not_home'
  action:
    - action: light.turn_off
      entity_id:
        - light.christmas_tree_switch
        - light.christmas_star
        - light.tv_christmas