- alias: 'Turn on christmas tree when motion in living'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: light.kerstboom
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.kerstboom

- alias: 'Turn on backyard christmas lights at sunset'
  trigger:
    - platform: sun
      event: 'sunset'
  action:
    - service: light.turn_on
      entity_id: light.kerstverlichting

- alias: 'Turn off christmas lights when leaving or sleeping'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - service: light.turn_off
      entity_id: light.kerstboom
    - service: light.turn_off
      entity_id: light.kerstverlichting

