- alias: 'Turn on backyard christmas lights at sunset'
  trigger:
    - platform: sun
      event: 'sunset'
  action:
    - service: light.turn_on
      entity_id: light.kerstverlichting

- alias: 'Turn off christmas lights when leaving or sleeping'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - service: light.turn_off
      entity_id: light.kerstverlichting

