- alias: 'Turn on christmas tree when motion in living'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: light.kerstboom
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.kerstboom

- alias: 'Turn on outside christmas lights at sunset'
  trigger:
    - platform: sun
      event: 'sunset'
  action:
    - service: switch.turn_on
      entity_id: switch.schuur_opladers
    - service: light.turn_on
      entity_id: light.christmas_frontyard

- alias: 'Turn on frontyard christmas lights when waking up'
  trigger:
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'off'
  action:
    - service: light.turn_on
      entity_id: light.christmas_frontyard
    - service: light.turn_on
      entity_id: light.christmas_star
    
- alias: 'Turn off frontyard christmas lights when sun is up'
  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '+00:30:00'
  action:
    - service: light.turn_off
      entity_id: light.christmas_frontyard

- alias: 'Turn off frontyard christmas lights at night'
  trigger:
    - platform: time
      at: '00:00:00'
  action:
    - service: light.turn_off
      entity_id: light.christmas_frontyard
    - service: light.turn_off
      entity_id: light.christmas_star

- alias: 'Turn off christmas lights when leaving or sleeping'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  action:
    - service: light.turn_off
      entity_id: light.kerstboom
    - service: switch.turn_off
      entity_id: switch.schuur_opladers