- alias: 'Notify when pressing the doorbell'
  trigger:
    - platform: state
      entity_id: binary_sensor.ring_voordeur_ding
      to: 'on'
  action:
    - service: tts.google_say
      data:
        entity_id: media_player.woonkamer_2
        message: 'Er staat iemand voor de voordeur'
