- alias: 'Notify when pressing the doorbell'
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_visitor
      to: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.doorbell_sub
        filename: !secret frontyard_snapshot_folder
    - service: tts.google_say
      data:
        entity_id: group.announcement_speakers
        message: 'Er staat iemand voor de voordeur'
    - service: notify.telegram_notify
      data_template:
        message: "Er is aangebeld bij de voordeur"
        data:
          photo:
            - url: !secret frontyard_snapshot_url
              caption: Er is aangebeld bij de voordeur
