- alias: 'Notify when pressing the doorbell'
  trigger:
    - platform: state
      entity_id: binary_sensor.doorbell_visitor
      to: 'on'
  action:
    - parallel:
      - service: notify.apps
        data:
          title: "Deurbel"
          message: "Er is aangebeld bij de voordeur om {{ now().strftime('%H:%M') }}."
          data:
            image: "/api/camera_proxy/camera.doorbell_sub"
            clickAction: "entityId:camera.doorbell_sub"
            ttl: 0
            vibrationPattern: "50, 200, 50, 500, 50"
            priority: high
            importance: high
            channel: Doorbell
            notification_icon: mdi:doorbell
      - service: camera.snapshot
        data:
          entity_id: camera.doorbell_sub
          filename: !secret frontyard_snapshot_folder
      - choose:
          - conditions:
              - condition: and
                conditions: 
                  - condition: state
                    entity_id: group.all_persons
                    state: 'home'
                  - condition: state
                    entity_id: input_boolean.night_mode
                    state: 'off'
            sequence:
              - service: tts.google_say
                data:
                  entity_id: group.announcement_speakers
                  message: 'Er staat iemand voor de voordeur'
