- alias: 'Notify when pressing the doorbell'
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur_ding
      to: 'on'
  action:
    - service: camera.snapshot
      data:
        entity_id: camera.frontyard
        filename: !secret frontyard_snapshot_folder
    - service: tts.google_say
      data:
        entity_id: media_player.woonkamer_mini
        message: 'Er staat iemand voor de voordeur'
    - service: notify.telegram_notify
      data_template:
        message: "Er is aangebeld bij de voordeur"
        data:
          photo:
            - url: !secret frontyard_snapshot_url
              caption: Er is aangebeld bij de voordeur
    - service: camera.play_stream
      data:
        entity_id: camera.frontyard
        media_player: media_player.home_hub
