- alias: 'Trigger fire alarm when smoke detected'
  trigger:
    - platform: state
      entity_id: binary_sensor.rookmelder_1ste_22
      to: 'on'
    - platform: state
      entity_id: binary_sensor.rookmelder_2de_133
      to: 'on'
    - platform: state
      entity_id: binary_sensor.rookmelder_bg_247
      to: 'on'
    - platform: state
      entity_id: binary_sensor.co_sensor_255
      to: 'on'
  action:
    - service: notify.all
      data_template:
        title: "*BRAND alarm!*"
        message: >
          Brandmelding of koolmonoxide melding op: {{ trigger.to_state.name }}
          Andere active sensors:
          {% for state in states.binary_sensor -%}
            {% if state.state == 'on' and state.name != 'Ping to Vera' %}
              {{ state.name }}
            {%- endif -%}
          {% endfor %}
    - service: light.turn_on
      entity_id: all
    - service: tts.google_say
      data:
        entity_id: group.announcement_speakers
        message: 'Er is brand gedetecteerd! Verlaat de woning!'
