- alias: 'Trigger fire alarm when smoke detected'
  trigger:
    - trigger: state
      entity_id: binary_sensor.hallway_1st_smoke_alarm
      to: 'on'
      for: 
        seconds: 5
    - trigger: state
      entity_id: binary_sensor.rookmelder_2de_280
      to: 'on'
      for: 
        seconds: 5
    - trigger: state
      entity_id: binary_sensor.hallway_gf_smoke_alarm
      to: 'on'
      for: 
        seconds: 5
    - trigger: state
      entity_id: binary_sensor.carbon_monoxide_detected
      to: 'on'
      for: 
        seconds: 5
  action:
    - action: notify.send_message
      target:
        entity_id: !secret telegram_notify_bot
      data_template:
        title: "*BRAND alarm!*"
        message: >
          Brandmelding of koolmonoxide melding op: {{ trigger.to_state.name }}
          Andere active sensors:
          {% for state in states.binary_sensor -%}
            {% if state.state == 'on' %}
              {{ state.name }}
            {%- endif -%}
          {% endfor %}
    - action: light.turn_on
      entity_id: all
    - action: tts.google_say
      data:
        entity_id: group.announcement_speakers
        message: 'Er is brand of koolmonoxide gedetecteerd! Verlaat de woning!'
