- alias: 'Trigger fire alarm when smoke detected'
  trigger:
    - platform: state
      entity_id: binary_sensor.rookmelder_1ste_22
      to: 'on'
    - platform: state
      entity_id: binary_sensor.rookmelder_2de_133
      to: 'on'
    - platform: state
      entity_id: binary_sensor.rookmelder_bg_3
      to: 'on'
  action:
    - service: notify.all
      data_template:
        title: "*BRAND alarm!*"
        message: >
          Brandmelding op:
          {% for state in states.binary_sensor -%}
            {% if state.state == 'on' and state.name != 'Wasmachine' and state.name != 'Ping to Vera' %}
              {{ state.name }}
            {%- endif -%}
          {% endfor %}
    - service: light.turn_on
      entity_id: group.all_lights
    - service: script.sonos_speak
      data:
        message: 'Er is brand gedetecteerd! Verlaat de woning!'
