- alias: 'Frontyard light on'
  trigger:
    - platform: sun
      event: 'sunset'
  action:
    - service: light.turn_on
      data:
        entity_id: light.buitenlicht_voorkant

- alias: 'Frontyard light off'
  trigger:
    - platform: sun
      event: 'sunrise'
      offset: '-00:20:00'
  action:
    - service: light.turn_off
      data:
        entity_id: light.buitenlicht_voorkant
