- alias: 'Notify when leaving the frontdoor open'
  trigger:
    - platform: state
      entity_id: binary_sensor.voordeur_200
      to: 'on'
      for:
        hours: 0
        minutes: 15
        seconds: 0
  action:
    - service: notify.all
      data:
        message: 'De voordeur staat al 10 minuten open'

