- alias: 'Turn on frontyard Chistmas lights'
  trigger:
    - trigger: time
      at: '6:00:00'
    - trigger: sun
      event: 'sunset'
  condition:
    - condition: state
      entity_id: light.frontyard_christmas_strings
      state: 'off'
  action:
    - action: light.turn_on
      data:
        entity_id: light.frontyard_christmas_strings

- alias: 'Turn off frontyard Christmas lights'
  trigger:
    - trigger: time
      at: '23:30:00'
    - trigger: sun
      event: 'sunrise'
  action:
    - action: light.turn_off
      data:
        entity_id: light.frontyard_christmas_strings