- alias: 'Turn on frontyard Chistmas lights'
  trigger:
    - trigger: sun
      event: 'sunset'
    - trigger: time
      at: '6:00:00'
  action:
    - action: light.turn_on
      data:
        entity_id: light.christmas_balcony_switch

- alias: 'Turn off backyard Christmas lights'
  trigger:
    - trigger: sun
      event: 'sunrise'
    - trigger: time
      at: '00:00:00'
  action:
    - action: light.turn_off
      data:
        entity_id: light.christmas_balcony_switch