- alias: 'Turn on Garden lights when the sun goes down'
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'home'
    - platform: sun
      event: 'sunset'
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: sun
      after: 'sunset'
  action:
    - service: light.turn_on
      data:
        entity_id: light.garden_lights_245

