- alias: 'Turn on ghost mode when away at night'
  trigger:
    - platform: time
      at: '22:00:00'
  condition:
    - condition: time
      after: '22:00:00'
    - condition: state
      entity_id: input_select.home_mode
      state: 'away'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.ghost_mode

- alias: 'Turn off ghost mode when coming home or at 1:00'
  trigger:
    - platform: time
      at: '01:00:00'
    - platform: state
      entity_id: input_select.home_mode
      to: 'home'
  condition:
    - condition: state
      entity_id: input_boolean.ghost_mode
      state: 'on'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.ghost_mode

- alias: 'Turn on kitchen lights when ghost mode enabled'
  trigger:
    - platform: time_pattern
      minutes: '/30'
      seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.ghost_mode
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen
        brightness: 30
    - delay: 0:15:00
    - service: light.turn_off
      entity_id: light.kitchen

- alias: 'Turn on Gang1ste when ghost mode enabled'
  trigger:
    - platform: time_pattern
      minutes: '/45'
      seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.ghost_mode
      state: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hallway_1st
        brightness: 40
    - delay: 0:20:00
    - service: light.turn_off
      entity_id: light.hallway_1st

- alias: 'Turn on GangBG when ghost mode enabled'
  trigger:
    - platform: time_pattern
      minutes: '/20'
      seconds: 0
  condition:
    - condition: state
      entity_id: input_boolean.ghost_mode
      state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.gang_bg
    - delay: 0:05:00
    - service: light.turn_off
      entity_id: light.gang_bg
