- alias: 'Turn on Gang1ste light when motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_1st_motion_detection
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: numeric_state
          entity_id: sensor.hallway_1st_illuminance
          below: 4
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.hallway_1st
        brightness: >
          {% if is_state('input_boolean.night_mode', 'on') %}
            30
          {% else %}
            80
          {% endif %}

- alias: 'Turn on Gang2de light when motion'
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_2nd_motion_detection
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: or
      conditions:
        - condition: state
          entity_id: sun.sun
          state: 'below_horizon'
        - condition: numeric_state
          entity_id: sensor.hallway_2nd_illuminance
          below: 1
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.hallway_2nd
        brightness: >
          {% if is_state('input_boolean.night_mode', 'on') %}
            30
          {% else %}
            80
          {% endif %}

- alias: 'Turn off Gang1ste light'
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_1st_motion_detection
      to: 'off'
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
  condition:
    - condition: state
      entity_id: light.hallway_1st
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.hallway_1st

- alias: 'Turn off Gang2de light'
  trigger:
    - platform: state
      entity_id: binary_sensor.hallway_2nd_motion_detection
      to: 'off'
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
  condition:
    - condition: state
      entity_id: light.hallway_2nd
      state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.hallway_2nd
