- alias: 'Turn on GangBG light when coming home'
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      from: away
      to: home
  condition:
    - condition: state
      entity_id: input_select.home_mode
      state: home
    - condition: sun
      after: 'sunset'
  action:
    - service: light.turn_on
      entity_id: light.gang_bg
    - delay: 0:10
    - service: light.turn_off
      entity_id: light.gang_bg
