- alias: 'Turn heating down when night mode activates'
  trigger:
    - trigger: state
      entity_id: input_select.home_mode
      to: night
  action:
    - action: climate.set_temperature
      data:
        entity_id: climate.heating
        temperature: 16

- alias: 'Turn heating down when leaving'
  trigger:
    - trigger: state
      entity_id: input_select.home_mode
      to: away
      for:
        hours: 1
  action:
    - action: climate.set_temperature
      data:
        entity_id: climate.heating
        temperature: 17

- alias: 'Turn heating up when coming home'
  trigger:
    - trigger: state
      entity_id: input_select.home_mode
      from: away
      to: home
  condition:
    - condition: time
      after: "07:00:00"
      before: "22:00:00"
    - condition: numeric_state
      entity_id: climate.heating
      attribute: temperature
      below: 18.5
  action:
    - action: climate.set_temperature
      data:
        entity_id: climate.heating
        temperature: 18.5