- alias: 'Turn living lights on'
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      from: away
      to: home
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.living_illuminance
      below: 6
  condition:
    - condition: state
      entity_id: input_select.home_mode
      state: home
    - condition: state
      entity_id:
        - light.living_spots
        - light.kitchen
      state: 'off'
      match: any
    - condition: numeric_state
      entity_id: sensor.living_illuminance
      below: 6
    - condition: state
      entity_id: light.partylight
      state: 'off'
  action:
    - if:
      - alias: TV is on
        condition: state
        entity_id: media_player.sony_bravia_tv
        state: 'on'
      - alias: It's evening
        condition: time
        after: '20:00:00'
      then:
      - alias: Turn on movie scene
        service: scene.turn_on
        entity_id: scene.living_movie
      else:
      - alias: Turn on living normal scene
        service: scene.turn_on
        entity_id: scene.living_normal

- alias: 'Turn living lights off when enough daylight or leaving or sleeping'
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_illuminance
      above: 6
    - platform: state
      entity_id: input_select.home_mode
      to:
        - away
        - night
  condition:
    - condition: state
      entity_id: light.living_spots
      state: 'on'
  action:
    - service: script.turn_living_lights_off

- alias: 'Turn living lights off when no activity'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'off'
      for:
        minutes: 45
  condition:
    - condition: state
      entity_id: input_select.home_mode
      state: home
    - condition: state
      entity_id:
        - light.living_spots
        - light.kitchen
      state: 'on'
      match: any
    - condition: state
      entity_id:
        - media_player.sony_bravia_tv
        - media_player.chromekamer
      state: 'off'
  action:
    - service: script.turn_living_lights_off

- alias: 'Living lights on during sleepmode'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'on'
  condition:
    - condition: state
      entity_id: input_select.home_mode
      state: night
    - condition: numeric_state
      entity_id: sensor.living_illuminance
      below: 6
  action:
    - service: scene.turn_on
      entity_id: scene.living_night

- alias: 'Living lights off during sleepmode'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'off'
      for:
        minutes: 15
  condition:
    - condition: state
      entity_id: input_select.home_mode
      state: night
  action:
    - service: script.turn_living_lights_off
