- alias: 'Turn living lights on'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'home'
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.living_illuminance
      below: 6
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: light.living_spots
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.living_illuminance
      below: 6
  action:
    - service: scene.turn_on
      entity_id: scene.living_normal

- alias: 'Turn living lights off when enough daylight or leaving'
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_illuminance
      above: 6
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
  condition:
    - condition: state
      entity_id: light.living_spots
      state: 'on'
  action:
    - service: script.turn_lights_off

- alias: 'Turn living lights off when no activity'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'off'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: light.living_spots
      state: 'on'
    - condition: state
      entity_id: media_player.sony_bravia_tv
      state: 'off'
  action:
    - service: script.turn_lights_off

- alias: 'Living lights on during sleepmode'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.living_illuminance
      below: 6
  action:
    - service: scene.turn_on
      entity_id: scene.living_night

- alias: 'Living lights off during sleepmode'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_motion_detection
      to: 'off'
      for:
        minutes: 15
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
  action:
    - service: script.turn_lights_off
