- alias: 'Living lights on'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'home'
    - platform: state
      entity_id: binary_sensor.living_sensor_119
      to: 'on'
    - platform: numeric_state
      entity_id: sensor.living_lux_130
      below: 7
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: light.woonkamer_spots_5
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.living_lux_130
      below: 7
  action:
    - service: scene.turn_on
      entity_id: scene.living_normal

- alias: 'Living lights off'
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_lux_130
      above: 12
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
  condition:
    - condition: state
      entity_id: light.woonkamer_spots_5
      state: 'on'
  action:
    - service: script.turn_lights_off

- alias: 'Living lights on during sleepmode'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_sensor_119
      to: 'on'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.living_lux_130
      below: 7
  action:
    - service: scene.turn_on
      entity_id: scene.living_night

- alias: 'Living lights off during sleepmode'
  trigger:
    - platform: state
      entity_id: binary_sensor.living_sensor_119
      to: 'off'
      for:
        minutes: 15
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
  action:
    - service: script.turn_lights_off
