- alias: 'Living lights on'
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'home'
    - platform: state
      entity_id: binary_sensor.living_sensor
      state: 'on'
    - platform: numeric_state
      entity_id: sensor.living_lux
      below: 7
  condition:
    - condition: state
      entity_id: group.all_devices
      state: 'home'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'off'
    - condition: state
      entity_id: light.woonkamer_spots
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.living_lux
      below: 7
  action:
    - service: scene.turn_on
      entity_id: scene.living_normal

- alias: 'Living lights off'
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_lux
      above: 12
    - platform: state
      entity_id: group.all_devices
      state: 'not_home'
  condition:
    - condition: state
      entity_id: light.woonkamer_spots
      state: 'on'
  action:
    - service: script.turn_lights_off
