- alias: Low battery level detection & notification for all battery sensors
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      day: '0'
      threshold: '15'
      time: '10:00:00'
      exclude:
        entity_id:
          - sensor.strips_mazw_battery_level
          - binary_sensor.strips_mazw_low_battery_level
      actions:
        - service: notify.persistent_notification
          data: 
            title: Low battery'
            message: Battery of {{ sensors }} is low

      