- alias: 'Dim lights when TV is on'
  trigger:
    - platform: state
      entity_id: media_player.chromekamer
      to: 'playing'
    - platform: state
      entity_id: media_player.sony_bravia_tv
      to: 'playing'
    - platform: state
      entity_id: light.living_spots
      to: 'on'
  condition:
    - condition: state
      entity_id: media_player.sony_bravia_tv
      state: 'playing'
    - condition: numeric_state
      entity_id: light.living_spots
      value_template: '{{ state.attributes.brightness|default(0) }}'
      above: 45
  action:
    - service: scene.turn_on
      entity_id: scene.living_tv

- alias: 'Turn off TV when leaving or sleeping'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
    - platform: state
      entity_id: input_boolean.night_mode
      to: 'on'
  condition:
    - condition: state
      entity_id: media_player.sony_bravia_tv
      state: 'playing'
  action:
    - service: media_player.turn_off
      entity_id: media_player.sony_bravia_tv
