- alias: 'Dim lights when TV is on'
  trigger:
    - trigger: state
      entity_id: media_player.chromekamer
      to: 'playing'
    - trigger: state
      entity_id: media_player.sony_bravia_tv
      to: 'on'
  condition:
    - condition: state
      entity_id: media_player.sony_bravia_tv
      state: 'on'
    - condition: numeric_state
      entity_id: light.living_spots
      attribute: brightness
      above: 50
    - condition: time
      after: '20:00:00'
  action:
    action: scene.turn_on
    entity_id: scene.living_movie

- alias: 'Turn off TV when leaving or sleeping'
  trigger:
    - trigger: state
      entity_id: input_select.home_mode
      to:
        - away
        - night 
  condition:
    - condition: state
      entity_id: media_player.sony_bravia_tv
      state: 'on'
  action:
    - action: media_player.turn_off
      entity_id: media_player.sony_bravia_tv
