- alias: 'Home coming'
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'home'
  action:
    - service: notify.all
      data:
        message: Welkom thuis!
    - service: shell_command.vera_home_mode
    - service: media_player.sonos_snapshot
      entity_id: media_player.woonkamer
    - service: media_player.media_pause
      entity_id: media_player.woonkamer
    - service: media_player.volume_set
      data:
        entity_id: media_player.woonkamer
        volume_level: 0.40
    - service: media_player.play_media
      data:
        entity_id: media_player.woonkamer
        media_content_type: 'MUSIC'
        media_content_id: https://s3-eu-west-1.amazonaws.com/tx-homeassistant/homecoming.mp3
    - delay: 0:00:5
    - service: media_player.sonos_restore
      entity_id: media_player.woonkamer

- alias: 'Leaving'
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - service: notify.all
      data:
        message: Afwezigheid gedetecteerd
    - service: shell_command.vera_away_mode
