- alias: 'Home coming'
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'home'
  action:
    - service: notify.all
      data_template:
        title: "Welkom thuis!"
        message: >
          Aanwezig:
          {% for state in states.device_tracker -%}
            {% if state.state == 'home' %}
              {{ state.name }}
            {%- endif -%}
          {% endfor %}
    - service: shell_command.vera_home_mode
    - service: script.sonos_speak
      data:
        message: 'Welkom thuis!'

- alias: 'Leaving'
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
  action:
    - service: notify.all
      data:
        message: Afwezigheid gedetecteerd
    - service: shell_command.vera_away_mode
