- alias: 'Home coming'
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'home'
  action:
    - service: notify.all
      data:
        message: Welkom thuis!
    - service: shell_command.vera_home_mode
    - service: script.sonos_speak
      data:
        message: 'Welkom thuis!'

- alias: 'Leaving'
  trigger:
    - platform: state
      entity_id: group.all_devices
      to: 'not_home'
  action:
    - service: notify.all
      data:
        message: Afwezigheid gedetecteerd
    - service: shell_command.vera_away_mode
