- alias: 'Home coming'
  trigger:
    - trigger: state
      entity_id: group.all_persons
      to: 'home'
  action:
    - action: notify.send_message
      target:
        entity_id: !secret telegram_notify_bot
      data_template:
        title: "Welkom thuis!"
        message: "Aanwezig: {{ states.person | selectattr('state','eq','home') | map(attribute='attributes.friendly_name') | list | join(', ') }}"
