- alias: 'Home coming'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'home'
  action:
    - service: notify.telegram_notify
      data_template:
        title: "Welkom thuis!"
        message: "Aanwezig: {{ state_attr(trigger.entity_id, 'friendly_name') }}"

    - service: rest_command.vera_home_mode
    - service: tts.google_say
      data:
        entity_id: media_player.woonkamer_mini
        message: 'Welkom thuis!'

- alias: 'Leaving'
  trigger:
    - platform: state
      entity_id: group.all_persons
      to: 'not_home'
  action:
    - service: notify.telegram_notify
      data:
        message: Afwezigheid gedetecteerd
    - service: rest_command.vera_away_mode
