- alias: 'Home coming'
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'home'
  action:
    - service: notify.all
      data:
        message: Welkom thuis!
    - service: shell_command.vera_home_mode
    - service: media_player.sonos_snapshot
      entity_id: media_player.woonkamer
    - service: media_player.media_pause
      entity_id: media_player.woonkamer
    - service: media_player.volume_set
      data:
        entity_id: media_player.woonkamer
        volume_level: 0.40
    - service: tts.google_say
      entity_id: media_player.woonkamer
      data:
        message: 'Welkom thuis en fijne dagen!'
    - delay: 0:00:5
    - service: media_player.sonos_restore
      entity_id: media_player.woonkamer

- alias: 'Leaving'
  trigger:
    - platform: state
      entity_id: group.all_devices
      state: 'not_home'
  action:
    - service: notify.all
      data:
        message: Afwezigheid gedetecteerd
    - service: shell_command.vera_away_mode
