- alias: 'Show available commands via Telegram'
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/help'
  action:
    - service: notify.telegram_notify
      data:
        message: 'commands'
        data:
          keyboard:
            - '/ping, /alarm'
