- alias: 'Start blink lights from Telegram'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/blinklights'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Blinking lights enabled'
    - service: notify.telegram_notify
      data:
        message: 'Blinking lights enabled'
        data:
          inline_keyboard:
            - 'Stop:/stop_blinklights'
    - service: script.start_blink_lights

- alias: 'Stop blink lights from Telegram'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/stop_blinklights'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Blinking lights disabled'
    - service: notify.telegram_notify
      data:
        message: 'Blinking lights disabled'
        data:
          inline_keyboard:
            - 'Blink lights:/blinklights'
    - service: script.stop_blink_lights

- alias: 'Disarm alarm'
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/disarm_alarm'
  action:
    - service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.home_alarm
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Alarm disarmed'
    - service: notify.telegram_notify
      data:
        message: '✅ Alarm disarmed'
