- alias: 'Notify when the vacuum robot is done'
  trigger:
    - platform: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      from: 'cleaning'
  condition:
    - condition: not
      conditions:
        - alias: "Don't trigger when the vacuum is unavailable"
          condition: state
          entity_id: vacuum.xiaomi_vacuum_cleaner
          state: "unavailable"
  action:
    - service: notify.all
      data_template:
        title: "*De robotstofzuiger is klaar!*"
        message: >
          Status: {{ states('vacuum.xiaomi_vacuum_cleaner') }}
          Tijd: {{ (int(states('sensor.xiaomi_vacuum_cleaner_last_clean_duration'))/60)|round }}mins.
          Oppervlakte: {{ states('sensor.xiaomi_vacuum_cleaner_last_clean_area') }}m2.

- alias: 'Notify the vacuum cleaner will run this night'
  trigger:
    - platform: time
      at: '22:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.automatic_vacuum_cleaner
      state: 'on'
  action:
    - service: notify.all
      data:
        message: "Vannacht gaat de robotstofzuiger aan de gang"

- alias: 'Set the vacuum cleaner to run upcoming night'
  trigger:
    - platform: time
      at: '05:00:00'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.automatic_vacuum_cleaner

- alias: 'Run the vacuum cleaner at night'
  trigger:
    - platform: time
      at: '01:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.automatic_vacuum_cleaner
      state: 'on'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
  action:
    - service: vacuum.start
      entity_id: vacuum.xiaomi_vacuum_cleaner
    - service: input_boolean.turn_off
      entity_id: input_boolean.automatic_vacuum_cleaner
