- alias: 'Notify when the vacuum robot is done'
  trigger:
    - platform: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      from: 'cleaning'
  action:
    - service: notify.all
      data_template:
        title: "*De robotstofzuiger is klaar!*"
        message: >
          Status: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.status }}
          Tijd: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaning_time }}mins.
          Oppervlakte: {{ states.vacuum.xiaomi_vacuum_cleaner.attributes.cleaned_area }}m2.

- alias: 'Notify the vacuum cleaner will run this night'
  trigger:
    - platform: time
      at: '22:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.automatic_vacuum_cleaner
      state: 'on'
  action:
    - service: notify.all
      data:
        message: "Vannacht gaat de robotstofzuiger aan de gang"

- alias: 'Set the vacuum cleaner to run upcoming night'
  trigger:
    - platform: time
      at: '5:00:00'
  condition:
    - condition: state
      entity_id: group.all_persons
      state: 'home'
    - condition: time
      weekday:
        - sun
        - tue
        - thu
        - fri
        - sat
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.automatic_vacuum_cleaner

- alias: 'Run the vacuum cleaner at night'
  trigger:
    - platform: time
      at: '1:30:00'
  condition:
    - condition: state
      entity_id: input_boolean.automatic_vacuum_cleaner
      state: 'on'
    - condition: state
      entity_id: input_boolean.night_mode
      state: 'on'
  action:
    - service: vacuum.start
      entity_id: vacuum.xiaomi_vacuum_cleaner
