- alias: 'Notify when the vacuum robot is done'
  trigger:
    - trigger: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      from: 'cleaning'
  condition:
    - condition: not
      conditions:
        - alias: "Don't trigger when the vacuum is unavailable"
          condition: state
          entity_id: vacuum.xiaomi_vacuum_cleaner
          state: "unavailable"
  action:
    - action: notify.send_message
      target:
        entity_id: !secret telegram_notify_bot
      data_template:
        title: "*De robotstofzuiger is klaar!*"
        message: >
          Status: {{ states('vacuum.xiaomi_vacuum_cleaner') }}
          Tijd: {{ (int(states('sensor.xiaomi_vacuum_cleaner_last_clean_duration'))/60)|round }}mins.
          Oppervlakte: {{ states('sensor.xiaomi_vacuum_cleaner_last_clean_area') }}m2.

- alias: 'Enable automatic vacuum cleaner on sleep mode'
  trigger:
    - trigger: state
      entity_id: input_select.home_mode
      to: night
  action:
    - action: input_boolean.turn_on
      entity_id: input_boolean.automatic_vacuum_cleaner

- alias: 'Run the vacuum cleaner when automatic vacuum cleaner is enabled'
  trigger:
    - trigger: state
      entity_id: input_boolean.automatic_vacuum_cleaner
      to: 'on'
    - trigger: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      to: 'docked'
  condition:
    - condition: state
      entity_id: input_boolean.automatic_vacuum_cleaner
      state: 'on'
  action:
    - action: vacuum.start
      entity_id: vacuum.xiaomi_vacuum_cleaner

- alias: 'Disable automatic vacuum cleaner when started cleaning'
  trigger:
    - trigger: state
      entity_id: vacuum.xiaomi_vacuum_cleaner
      to: 'cleaning'
  condition:
    - condition: state
      entity_id: input_boolean.automatic_vacuum_cleaner
      state: 'on'
  action:
    - action: input_boolean.turn_off
      entity_id: input_boolean.automatic_vacuum_cleaner