- alias: 'Turn on ventilation when CO2 level high'
  trigger:
    - platform: numeric_state
      entity_id: sensor.6_in_1_multisensor_light
      above: 1200
  action:
    - service: switch.turn_on
      entity_id: switch.ventilatie

- alias: 'Turn off ventilation after 2 hours'
  trigger:
    - platform: state
      entity_id: switch.ventilatie
      state: 'on'
  action:
    - delay: 2:00:00
    - service: switch.turn_off
      entity_id: switch.ventilatie
