- alias: 'Turn on ventilation when CO2 level high'
  trigger:
    - platform: numeric_state
      entity_id: sensor.netatmo_indoor_co2
      above: 1200
  condition:
    - condition: state
      entity_id: switch.mechanical_ventilation
      state: 'off'
    - condition: state
      entity_id: input_select.home_mode
      state:
        - home
        - night
  action:
    - service: switch.turn_on
      entity_id: switch.mechanical_ventilation

- alias: 'Turn on ventilation when using hot water for more than 3 minutes'
  trigger:
    - platform: state
      entity_id: binary_sensor.hotwater_active
      to: 'on'
      for:
        minutes: 3
  condition:
    - condition: state
      entity_id: switch.mechanical_ventilation
      state: 'off'
    - condition: state
      entity_id: input_select.home_mode
      state:
        - home
        - night
  action:
    - service: switch.turn_on
      entity_id: switch.mechanical_ventilation

- alias: 'Turn off ventilation after 2 hours'
  trigger:
    - platform: state
      entity_id: switch.mechanical_ventilation
      to: 'on'
  action:
    - delay: 2:00:00
    - service: switch.turn_off
      entity_id: switch.mechanical_ventilation

- alias: 'Turn off ventilation when activating night mode'
  trigger:
    - platform: state
      entity_id: input_select.home_mode
      to: night
  condition:
    - condition: state
      entity_id: switch.mechanical_ventilation
      state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.mechanical_ventilation
