- alias: 'Notify when Vera is unreachable'
  trigger:
    - platform: state
      entity_id: binary_sensor.ping_to_vera
      to: 'off'
  action:
    - service: notify.all
      data:
        message: Vera Edge is onbereikbaar!

- alias: 'Notify when Vera is back online'
  trigger:
  - platform: state
    entity_id: binary_sensor.ping_to_vera
    to: 'on'
  action:
  - service: notify.all
    data:
        message: Vera Edge is weer bereikbaar
