- alias: 'Deactivate night mode'
  trigger:
    - platform: time
      at: '6:30:00'
  condition:
    - condition: time
      after: '6:30:00'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.night_mode
