- alias: 'Notify when the washing machine is finished'
  trigger:
    - platform: state
      entity_id: sensor.wasmachine_operation_state
      to: 'Ready'
    - platform: state
      entity_id: sensor.wasmachine_operation_state
      to: 'Finished'
  action:
    - service: notify.app_tim
      data:
        message: 'De wasmachine is klaar'
    - service: tts.google_say
      data:
        entity_id: media_player.woonkamer_mini
        message: 'De wasmachine is klaar'
