- alias: 'Notify when the washing machine is finished'
  trigger:
    - platform: state
      entity_id: binary_sensor.washing_machine_state
      to: 'off'
  action:
    - service: notify.apps
      data:
        message: 'De wasmachine is klaar'
    - service: tts.google_say
      data:
        entity_id: media_player.woonkamer_mini
        message: 'De wasmachine is klaar'
