- alias: 'Notify when the wash dryer is finished'
  trigger:
    - platform: state
      entity_id: binary_sensor.wash_dryer_state
      to: 'off'
      for:
        minutes: 3
  condition:
    - condition: not
      conditions:
        - alias: "Don't trigger when the wash dryer is unavailable"
          condition: state
          entity_id: binary_sensor.wash_dryer_state
          state: "unavailable"
  action:
    - service: notify.app_tim
      data:
        message: 'De wasdroger is klaar'
    - service: tts.google_say
      data:
        entity_id: media_player.woonkamer_mini
        message: 'De wasdroger is klaar'
