- alias: 'Notify when the wash dryer is finished'
  trigger:
    - platform: state
      entity_id: binary_sensor.wash_dryer_state
      to: 'off'
      for:
        hours: 0
        minutes: 2
        seconds: 0
  action:
    - service: notify.all
      data:
        message: 'De wasdroger is klaar'
    - service: tts.google_say
      data:
        entity_id: media_player.woonkamer_2
        message: 'De wasdroger is klaar'
