- alias: 'Notify when washing machine is finished'
  trigger:
    - platform: state
      entity_id: binary_sensor.wasmachine_state
      state: 'off'
      for:
        hours: 0
        minutes: 2
        seconds: 0
  action:
    - service: notify.all
      data:
        message: Wasmachine is klaar
    - service: script.sonos_speak
      data:
        message: 'De wasmachine is klaar'
