- alias: Wasmachine notify
  trigger:
    - platform: state
      entity_id: binary_sensor.wasmachine_state
      state: 'off'
      for:
        hours: 0
        minutes: 2
        seconds: 0
  action:
    - service: notify.all
      data:
        message: Wasmachine is klaar
    - service: media_player.sonos_snapshot
      entity_id: media_player.woonkamer
    - service: media_player.media_pause
      entity_id: media_player.woonkamer
    - service: media_player.volume_set
      data:
        entity_id: media_player.woonkamer
        volume_level: 0.40
    - service: tts.google_say
      entity_id: media_player.woonkamer
      data:
        message: 'De wasmachine is klaar'
    - delay: 0:00:5
    - service: media_player.sonos_restore
      entity_id: media_player.woonkamer
