- alias: Wasmachine notify
  trigger:
    - platform: state
      entity_id: binary_sensor.wasmachine_state
      state: 'off'
      for:
        hours: 0
        minutes: 2
        seconds: 0
  action:
    - service: notify.all
      data:
        message: Wasmachine is klaar
