- alias: 'Notify when wind conditions are bad'
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_forecast_wind_speed
      above: 8
    - platform: numeric_state
      entity_id: sensor.weather_forecast_wind_direction
      above: 190
      below: 350
  condition:
    - condition: numeric_state
      entity_id: sensor.weather_forecast_wind_direction
      above: 190
      below: 350
    - condition: numeric_state
      entity_id: sensor.weather_forecast_wind_speed
      above: 8
  action:
    - service: notify.all
      data_template:
        message: 'Vanaf {{ (as_timestamp(now()) | int + (8*60*60)) | timestamp_custom("%H:%M") }} neemt de wind neemt toe en komt uit het westen: {{ states("sensor.weather_forecast_wind_speed") }}/ms'
